### ISSUE TITLE
Jscript

### ISSUE THREAD

**Issue by Tbo29** [WhiteNeo/lastposter-avatar-mybb18x-series#1]
Hola Dark Neo, te conviertes en blanco? Qué pasa con tu sitio?

Se pregunta de saber si este plugin es definitiva, ya que aún contiene el código anterior. He probado y creo que funciona bien. Cuando están activos en Mybb me dice algunos errores de una declaración  ilegal, pero es tan rápido que no puedo entender lo que es.

Saludos

**Comment by WhiteNeo** [comment]
El sitio esta caido ya que el proveedor no nos responde, estamos viendo que cosa.

La versión definitiva no hay hasta que no salga MyAlerts bien.

Sin embargo esta será la version más estable y funcional hasta que haga las pruebas que tengo que hacer, de momento funciona bien en mi sitio, sin embargo debo seguir probando, la versión anterior es la más funcional, aunque esta deberá ser la mejor y funcional.

Saludos...

**Comment by Tbo29** [comment]
Bueno, por lo que puedo modificar el plugin para encajar con mi thema. Usted ha visto el popup modal. Así que es más ligero y sin javascript.

Si tienes una idea de cómo adaptar el propup perfil para los Avatars de Myalerts? Yo, sin embargo, he hecho y funciona bien, però se utilizo el plugin de Google Seo no funciona.

Podría ser de agregar un hook de tu plugin en MyAlerts? O tengo que editar funcions.php?


.

**Comment by WhiteNeo** [comment]
Hay varias formas de hacerlo, yo uso MyAlerts y también uso Google SEO asi que no creo sea ese el problema, tienes la url de tu sitio para mirar que cosa.

Lo del tema lo puedes hacer mediante la modificación del estilo global modal ahi verás los datos de acomodar las cosas y lo demás esta en la hoja de estilo avatarep.css

De las alertas igualmente con el agregado del css debe funcionar bien.

Yo por ejemplo uso este código y funciona bien en el css de alerts.css

[code]

.alert--unread{
   font-size: 13px;
   background-color: #d8fcd4 !important;
}

.alert--read{
   font-size: 13px;
   background-color: #ffffff !important;
}

.alert__content a:link{
  color: #424242;
}

.alert__content a:visited{
   background-color: #ffffff !important;
   color: #F31D1D;
}

.alert--thanks img, .alert--mentionme img, .alert--myprofile img, .alert--rep img, .alert--pm img, .alert--buddylist img, .alert--quoted img, .alert--post_threadauthor img{
  border: 1px solid transparentt;
  width: 44px;
  height: 44px;
  border-radius: 4px;
  box-shadow: 1px 1px 4px 2px #d8fcd4;
  padding: 5px;
  margin: 5px 10px;
}
[/code]

**Comment by Tbo29** [comment]
Gracias. Voy aver el CSS. Mi foro he convertido a la versión 1.8.3, y cuando hago los últimos cambios  puedo darte un login de sesión.

La dirección es: forum.peru4you.de

**Comment by WhiteNeo** [comment]
Vale me voy a regitrar asi te ayudo y ya vemos que esto sea cerrado entonces como problema :D Saludos...

**Comment by Tbo29** [comment]
Es un placer conocer a gente como tú. Vi que te registraste. Por el momento he soluzionato casi todo. Ahora quiero integrar tu plugin Thk y ver si puedo usarlo como Like modificando la edición de la CSS y texto.

¿Qué te parece, en general, de mi thema? De buena gana aceptar tus críticas.

Con tu CSS para el sistema MyAlerts si ha resuelto el problema de la memoria caché de los avatares y tamaño de el plugin MyAlerts.

No sé cómo hacer un pullrequest, entonces yo digo aquí. 

En línea 222 de tu plugin Avatarep se puede agrega el codigo 

{$ lang-> total_threads} {$ memprofile [\ 'threadnum \']} <br /> 

El texto ya está en el archivo de idioma.

Espero que puedan resolver el problema pronto su sitio. Lamentablemente no creo que puedo ayudar a que mi proveedor está en alemania. Pero tal vez que si pueda.

**Comment by WhiteNeo** [comment]
Si, de hecho habría que editar la plantilla manualmente lo voy a agregar ya que eso por defecto no venía en MyBB 1.6 y se me paso por completo es una buena inovación que agregar :+1: D

Lo haré en estos días ya que acabo de corregir un bug de los grupos adicionales que no veían el avatar en zonas privadas, nisiquiera el nombre de usuario, sólo mostraba el asunto, en fin, ya está corregido y con esto sería algo más que agregar :dancer: 

Mi sitio creo que en definitiva no regresará sino dentro de algún tiempo que pueda arreglar algunos asuntos y que nuestra administradora aparezca ya que ella es la que lleva todo eso y no la he localizado, creo que algo le sucedío y me tiene más consternado lo que le pueda suceder a ella que al mismo foro :D

**Comment by WhiteNeo** [comment]
ya estamos en linea de nuevo.

http://soportemybb.es
