### ISSUE TITLE
Is there a way to grab the avatar and place it into my header?

### ISSUE THREAD

**Issue by LewisHolt** [WhiteNeo/lastposter-avatar-mybb18x-series#6]
I'm working on a header and it would look much better with an avatar, I've got your plugin installed and I was wondering if there's any... global avatar variable or something? I would like to find a way to implement an avatar into my header though. :)

Thanks! Love the plugin by the way, took a bit of fiddling around to set it up how I wanted but its superb.

**Comment by WhiteNeo** [comment]
mybb has own avatar global var for only current logued in user.

$mybb->user['avatar']

plugin is to load avatars where are not loaded but not global to not
overload with unnecesary data.

**Comment by LewisHolt** [comment]
Brilliant. 

I didn't know that MyBB had an option to do that by default.

Just in case anybody stumbles upon this and needs an answer, here you go. 

`<img src="{$mybb->user['avatar']}" alt="Avatar" width="60px" height="60px" /></div>`
