### ISSUE TITLE
wrong url?

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/lastposter-avatar-mybb18x-series#8]
https://github.com/WhiteNeo/lastposter-avatar-mybb18x-series/blob/master/inc/plugins/avatarep.php#L479

**Comment by WhiteNeo** [comment]
That was to remove old posible entries to deal with plugin and prevent to conflicto with two instances of js, and make a cleanup of templates if necesary only.

**Comment by WhiteNeo** [comment]
I will remove and depure this in next major version 2.9.9
